global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'federate'
    honor_labels: true
    metrics_path: /federate
    params:
      match[]:
        - '{job="prometheus"}'
        - '{job="generator"}'
        - '{__name__=~"^job:.*"}'
    static_configs:
      - targets:
        - 'prometheus:9090'
